---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
setwd("C:/Users/spencer.ng/Desktop/TH training/R Code Training MMM/Reproducible Research/FITBIT")
FITBIT <- read.csv("activity.csv", header=TRUE)
head(FITBIT)
str(DAILYSTEPS)
DAILYSTEPS <- aggregate(steps~date, FITBIT, sum)
head(DAILYSTEPS)
hist(DAILYSTEPS$steps)

## What is mean total number of steps taken per day?
averageDAILYSTEPS<- mean(DAILYSTEPS$steps)
averageDAILYSTEPS
medianDAILYSTEPS<- median(DAILYSTEPS$steps)
medianDAILYSTEPS





## What is the average daily activity pattern?
STEPSperINTERVAL <- aggregate(steps~interval, FITBIT, mean)
head(STEPSperINTERVAL)
with(STEPSperINTERVAL, plot(interval, steps
                        , type="l", main="mean#steps within 5-min interval"
                        , col = "red")) 
                        
MAXSTEPS <- max(STEPSperINTERVAL$steps)
MAXSTEPSperINTERVAL <- subset(STEPSperINTERVAL, steps == MAXSTEPS)
MAXSTEPSperINTERVAL$interval

## Imputing missing values
colSums(is.na(FITBIT))
FITBIT$stepsnew <- STEPSperINTERVAL$steps
head(FITBIT)
FITBIT$steps[is.na(FITBIT$steps)] <- FITBIT$stepsnew
head(FITBIT)

##Histogram of the total number of steps taken each day after missing values are imputed
DAILYSTEPS1 <- aggregate(steps~date, FITBIT, sum)
head(DAILYSTEPS1)
hist(DAILYSTEPS1$steps)

##report the mean and median total number of steps taken per day
averageDAILYSTEPS1<- mean(DAILYSTEPS1$steps)
averageDAILYSTEPS1
medianDAILYSTEPS1<- median(DAILYSTEPS1$steps)
medianDAILYSTEPS1

##Difference in mean & median after imputation of steps into NA
averageDAILYSTEPS1- averageDAILYSTEPS
medianDAILYSTEPS1- medianDAILYSTEPS


## Are there differences in activity patterns between weekdays and weekends?
install.packages("timeDate")
library(timeDate)
FITBIT$WD <- isWeekday(FITBIT$date)
head(FITBIT)

weekdayFITBIT <- subset(FITBIT, FITBIT$WD == "TRUE")
weekdayFITBITMean <- aggregate(steps ~ interval, weekdayFITBIT, mean)
head(weekdayFITBITMean)

weekendFITBIT <- subset(FITBIT, FITBIT$WD == "FALSE")
weekendFITBITMean <- aggregate(steps ~ interval, weekendFITBIT, mean)
head(weekendFITBITMean)

##Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
plot(weekdayFITBITMean$interval, weekdayFITBITMean$steps
     , xlab = "interval", ylab = "#steps"
     , main ="Weekday", col ="red", type="l") 

plot(weekendFITBITMean$interval, weekendFITBITMean$steps
     , xlab = "interval", ylab = "#steps"
     , main ="Weekend", col ="red", type="l")
